[env:nrf52832_custom]
extra_scripts = upload_hooks.py
platform = nordicnrf52
board = nrf52_dk
framework = arduino

; Upload via CMSIS-DAP (DAPLink) - J-Link OB DAPLink programmer
upload_protocol = cmsis-dap
debug_tool = cmsis-dap

; Serial monitor speed
monitor_port = socket://localhost:9090
monitor_speed = 115200

build_flags =
    -DNRF52832_XXAA        ; ensure nRF52832 register map is included

lib_deps =
    koendv/RTT Stream@^1.3.0

