[env:nrf52832_custom]
platform = nordicnrf52
board = adafruit_feather_nrf52832
framework = arduino

; Upload via CMSIS-DAP (DAPLink) - J-Link OB DAPLink programmer
upload_protocol = cmsis-dap
debug_tool = cmsis-dap

; Serial monitor speed
monitor_port = socket://localhost:9090
monitor_speed = 115200

lib_ldf_mode = deep

build_flags =
    -I include

lib_deps =
    adafruit/Adafruit LIS3DH
    adafruit/Adafruit Unified Sensor
    mathertel/OneButton
    adafruit/Adafruit BusIO
    adafruit/Adafruit SleepyDog Library
